### PR TITLE
Extract `Applications` object

### PR DESCRIPTION
**Pull request by pberkes**
Ok so this might look scarily large, but this is all that happened:
- I extracted an `Applications` object, which is in charge of keeping a list of `applicants`, answering queries about them, and keeping changes to them in sync with the `config` files. That is basically just stuff that was in `Grader`, that got moved in `Applications`
- That allowed me to add some tests. This means that the new functionality works, but I might have broken the earlier, untested stuff. I have tested it manually but you never know.

The easiest way to review the PR might be to look at it commit by commit, since most of them are small refactoring steps.

More logic could be moved to `Applications`, in particular regarding the applicant gradings. If you like this PR I'll do that, as well.

Fix #4

### CODE REVIEW

**Comment by otizonaizit** [comment]
We are using grader right now to work with the applications for ASPP-APAC, so that's a perfect test bed ;)

I'll merge this into a separate branch `refactor`, so that we can test it while we go. I'd also like to see a second PR which moves the gradings logic to the new `Applications` object. You could base that PR on top of the new `refactor` branch, to which I will also commit any fixes for bugs we'll discover along the way while working on ASPP-APAC. This PR and the new one should allow us in the long run to get right of the namedtuples, right? Yeah! :))

**Comment by otizonaizit** [comment]
OK, sorry, I didn't see that the PR is **already** on a separate branch in the main repo. OK, so nothing to do on my side, I'd just propose you branch from `extract-applications` for the new PR, and I'll commit to `extract-applications` if I find bugs. OK?

**Comment by pberkes** [comment]
Ok great, keep your eyes open for bugs.

What's the feeling regarding making grader a package? Just for hygiene

**Comment by otizonaizit** [comment]
Regarding make grader a package: see #8 ;)

**Comment by otizonaizit** [comment]
I found an incompatibility with the old applications list: in the plugin `create_groups`, but maybe elsewhere in the code, we used to iterate over applications like:

```
for person in applications:
   do_something_with(person)
```

The `Applications` object is not iterable anymore. In other parts of the code, for example in `do_dump` to get all people matching a certain label we were doing:

```
persons = tuple(self._filter(*labels))
```

this feels cumbersome, I'd say we should add a `filter` method to Applications, which works like grader._filter, which returns a list of applications matching the given criteria. Maybe `filter` should grow its capabilities to return a list of applications matching a combination of labels and/or a combination of attributes and their values (like in return all applicants with `nationality=='Italy'`). What do you think?
I thought of making Applications a subclass of `list`, but I think that doesn't solve the filtering problem, which is the main usecase of iterating over applications…

**Comment by otizonaizit** [comment]
another issue. Command `rank` is broken:

```
grader> rank
----------------------------------------------------------------------
programming error: 'Grader' object has no attribute '_labels'
Traceback (most recent call last):
  File "./grader", line 1308, in main
    cmd.cmdloop()
  File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "./grader", line 790, in do_rank
    labels = self._labels(person.fullname)
AttributeError: 'Grader' object has no attribute '_labels'
```
The problem here is again the fact the `person` object in the failing line `self._labels(person.fullname)` is actually an item in a for loop over the result of a `grader._filter` call… This will be fixed once we have a `filter ` method on Applications. We can then subsitute all calls to `self._filter` with the new method and it should be working…

**Comment by pberkes** [comment]
Argh I missed rank, and yes I hadn't checked the plugin. I'll fix this evening.

Most of the time, instead of iterating on applications you need to iterate over applications.applicants

**Comment by otizonaizit** [comment]
I have implemented the above mentioned idea with a `filter` method. Now this needs to be used instead of `Grader._filter` everywhere!
Btw: thanks @pberkes for making grader testable: it was a pleasure to add the tests for the newly implemented method :))))

**Comment by pberkes** [comment]
@otizonaizit IIRC `_filter` is sometimes called with a list of `Person` objects created on the fly. How do we address that case? E.g. somewhere there is a `todo` list of applicants that is then filtered

**Comment by otizonaizit** [comment]
Those cases were needed because filter was not filtering by attribute, i.e. the list on the fly is created by selecting the applications based on some attributes. I think all use cases are covered by my implementation. Actually, I want to change the syntax, so that the implementation becomes more straightforward…

**Comment by otizonaizit** [comment]
I find the way to specify labels and their negations cumbersome in the `filter` method. And we can not negate attributes, so we can't filter for `nationality!='Italy'`. Can you come up with a nice syntax? I tried `filter(nationality='!Italy'` but that does not work for non-string attributes like `female` or birthyear…

**Comment by pberkes** [comment]
@otizonaizit my secret plan was to do a later PR to add `Applications.to_dataframe()`, in which case you could to things like
```
df = applications.to_dataframe()
df[~df.nationality == 'Italy']
```
and other cool things like pivot tables, ...

**Comment by pberkes** [comment]
ok I'm fixing `rank` now so scream if you are also touching the code

**Comment by otizonaizit** [comment]
I am done for today, so you are welcome to fix 'rank' :)

**Comment by otizonaizit** [comment]
The export to dataframe is surely cool, but in order for the results to be useful we need to also be able to re-import the dataframe into grader in a way that the rest of grader understands… so I fear that for that we'll have to port the whole of grader to a pandas dataframe… I am not in principle against that, I am just afraid it would be a lot of work…

**Comment by pberkes** [comment]
no no you can just ask for a dataframe object for doing stats, the rest would stay the same

**Comment by pberkes** [comment]
@tiziano I fixed `do_rank` and the plugin, and used `filter` wherever I could. I could not get `_filter` out of `do_grade` and `do_stat`

**Comment by otizonaizit** [comment]
I got rid of `Grader._filter` in the two remaining cases and added iteration capabilities to the `Applications` object. I am merging the PR!

**Comment by pberkes** [comment]
Nooo why should the applications object be iterable?

**Comment by pberkes** [comment]
And the magic with `__getitem__`! :-(

**Comment by otizonaizit** [comment]
what do you mean why? Because its use in grader is mostly to loop over all applications (or a filtered version thereof). The magic with `__getitem__` makes it possible to just use `applications` without depending on its internal definition, no? It basically boils down to have `for p in self.applications` instead of `for p in self.applications.applicants`. Not sure why the latter is more informative than the former…

**Comment by pberkes** [comment]
Well `applications` contains everything related to the applications of a given school edition, not just the applicants (basically everything that it's in config).`Applications` could easily grow an API to access that information as well in the future. Making it an iterator over applications it's confusing... and you don't gain much, since `applications.applicants` is the iterator you were looking for, much more explicit

**Comment by pberkes** [comment]
Before `Grader.applications` was just a list of applicants, and the `config` part was missing.

**Comment by pberkes** [comment]
This makes me especially sad: `self.applications.to_list()` instead of `self.applications.applicants`
😭

**Comment by otizonaizit** [comment]
I am not sure I agree. The richness of the new object Applications is not hidden by making it iterable. The only thing I agree with is that `to_list` is not good, but this can be easily removed. Regarding the rest, now the Applications contains everything and not only a list of applicants, I am still going to use that *within* grader most of the times as a list of applications. The new thing is that now I can finally access the labels and get a filtered list of the applications without messing up with the grader object…
So why forcing me to depend on the internal class attributes layout of Applications, and type 15 times in the code `for p in applications.applicants` instead of `for p in applications`?

**Comment by otizonaizit** [comment]
so, in other words, `Applications` is a proxy to the underlying list `applicants`, which takes care of merging the info from the csv files and the config files. So why not making the proxy transparent by allowing me to iterate over it like I used to be able to do before?

**Comment by otizonaizit** [comment]
fixed conflicts with current master

**Comment by pberkes** [comment]
I prefer the transparency of using the attribute directly: that way it's explicit what you are doing. In the other case, you are hiding what is going on, and to understand something like `len(applications)` you need to go to another file and see what is going on. On top of that, you never know what `Applications` might become in the future with respect to its other responsibilities.

But it's your library, and this is a design issue, so you are free to make `Applications` a chimera half-list-half-object 😛 

Ready to merge?

**Comment by otizonaizit** [comment]
OK, compromise: what about returning the iterator over the list of applications by calling `iter(applications)`, or, maybe easier to use,  `applications()` by implementing `__call__`?

**Comment by otizonaizit** [comment]
But it is a bit more convincing the fact that if `Applications` should grow additional responsobilities then it may become ambiguous what it means to iterate over it…

**Comment by pberkes** [comment]
Anyway for getting rid of `_filter`: 👍 👍 👍

**Comment by pberkes** [comment]
no no if you think of `Applications` as an interface for `applicants` then keep it as it is. The other suggestions are even worse 😉   "[...] `applications()` by implementing` __call__`" 😱 
The confusion already started with `filter`, which is really `filter_applicants`

**Comment by pberkes** [comment]
ok LGTM

**Comment by pberkes** [comment]
Merging, will move the grading functions in a later PR

**Pull request merged**
