### PR TITLE
Use pattern matching to process user input during grading

### PR DESCRIPTION
**Pull request by jakobj**
For some reason I looked at the code and it seemed like it could be cleaned up a bit using `match`. In addition I
- removed the `+`/`-`/`abs...` options, since I've never used them; they may be legacy?
- now avoid throwing an error when invalid input is detected; looks to me like we can just loop around in that case

I can't test it easily as the master branch seems to be broken and we don't have tests. :roll_eyes: 

What do you think?

### CODE REVIEW

**Comment by otizonaizit** [comment]
funny, I always voted using '+' and '-', never used the numbers ;-)

**Comment by otizonaizit** [comment]
regading the master branch: there is where the rewriting is happening. You should use the bilbao branch for now.

**Review by otizonaizit — COMMENTED** [review]
I would approve if you would test this against the current database of ASPP-LatAm. When the re-write is finished we will have real unit tests for these stuff. You should rebase this PR on top of the bilbao branch.

**Comment by jakobj** [comment]
oopsie, then I'll quickly include +/- again. would you also like to use =? ;)

re: branch, sure no problem. will rebase and test it in my ~ongoing~test grading session.

**Comment by otizonaizit** [comment]
ohh, yes, '=' too :-)

**Pull request closed without merging**
